package Throwable.Exception;

public class BadAttributeValueExpException {
   public static void main(String[] args) {
      try {
         System.out.println("ExpresiOn de valor de atributo creada exitosamente");
      } catch (Exception var2) {
         System.err.println("Error: " + var2.getMessage());
      }

   }
}
